fixed error redirection

diff --git a/hooks/network b/hooks/network
--- a/hooks/network
+++ b/hooks/network
@@ -7,14 +7,13 @@
 # Most of the functions not defined here or in default that are called here
 # are likely defined there. If you want to override them, you can redefine
 # them in a script here qemu.d/<vm_name>/<hook_name>/<state_name>/
-source "${0%/network}/default" "${@}" "<" "/dev/stdin"
+source "${0%/network}/default"
 
 # Calls the relevant function based on the hook name and VM state
 if [ -n "$(command -v "${HOOK_NAME/-/_}_${STATE_NAME}")" ]; then
-    echo "--------------NEXT--------------" >> "${LOG_FILE}"
-    echo "$(date): ${0} ${@}" >> "${LOG_FILE}"
-    eval \"${HOOK_NAME/-/_}_${STATE_NAME}\" &>> "${LOG_FILE}"
+    eval \"${HOOK_NAME/-/_}_${STATE_NAME}\" >> "${LOG_FILE}" 2> >(tee -a /dev/stderr)
 else
-    echo "ERROR: Function not found: ${HOOK_NAME/-/_}_${STATE_NAME}" >> "${LOG_FILE}"
+    echo "ERROR: Function not found: ${HOOK_NAME/-/_}_${STATE_NAME}" | tee -a "${LOG_FILE}" 1>&2
     declare -F >> "${LOG_FILE}"
+    exit 2
 fi
diff --git a/hooks/qemu b/hooks/qemu
--- a/hooks/qemu
+++ b/hooks/qemu
@@ -7,14 +7,15 @@
 # Most of the functions not defined here or in default that are called here
 # are likely defined there. If you want to override them, you can redefine
 # them in a script here qemu.d/<vm_name>/<hook_name>/<state_name>/
-source "${0%/qemu}/default" "${@}" "<" "/dev/stdin"
+source "${0%/qemu}/default"
 
 # Calls the relevant function based on the hook name and VM state
 if [ -n "$(command -v "${HOOK_NAME}_${STATE_NAME}")" ]; then
-    echo "--------------NEXT--------------" >> "${LOG_FILE}"
-    echo "$(date): ${0} ${@}" >> "${LOG_FILE}"
-    eval \"${HOOK_NAME}_${STATE_NAME}\" &>> "${LOG_FILE}"
+    eval \"${HOOK_NAME}_${STATE_NAME}\" >> "${LOG_FILE}" 2> >(tee -a /dev/stderr)
+    # @TODO: Figure out how to write the error messages to the log file without
+    #        redirecting them from stderr entirely
 else
-    echo "ERROR: Function not found: ${HOOK_NAME/-/_}_${STATE_NAME}" >> "${LOG_FILE}"
+    echo "ERROR: Function not found: ${HOOK_NAME/-/_}_${STATE_NAME}" | tee -a "${LOG_FILE}" 1>&2
     declare -F >> "${LOG_FILE}"
+    exit 2
 fi
